# Generated by Django 4.2.2 on 2023-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='coloca tu nombre', max_length=64)),
                ('apellido', models.CharField(help_text='Coloca tu apellido', max_length=64)),
            ],
        ),
    ]
