# Generated by Django 4.2.2 on 2023-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_remove_directores_cine_peliculas_dirigidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores_cine',
            name='peliculas_dirigidas',
            field=models.ManyToManyField(to='miapp.peliculas'),
        ),
    ]
